#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#define SERVER_PING_TIME 60000
#define SERVER_PACKET_TIMEOUT 2000

#define CLIENT_UPDATE_INTERVAL_MIN 2000
#define CLIENT_UPDATE_INTERVAL_MAX 60000

#define AGENT_UPDATE_INTERVAL_MIN 4000
#define AGENT_UPDATE_INTERVAL_MAX 60000

#endif
